### PR TITLE
Update .github repo to Tier 3 Repository Template

### PR DESCRIPTION
**Pull request by natalialuzuriaga**
## Problem

We have made significant updates to our repository templates and did not get the chance to update the `.github` repo to reflect the latest version.

## Solution

Updated `.github` repo to be our Tier 3 Repository Template

### CODE REVIEW

**Comment by natalialuzuriaga** [comment]
Do we still want `example-spdx-headers.md` and `insert_license_headers.sh`?

**Comment by natalialuzuriaga** [comment]
PR for #1 and kinda #2

**Comment by decause-gov** [comment]
> Do we still want `example-spdx-headers.md` and `insert_license_headers.sh`?

I am +1 to keep these for now, and recommend we explore when/where to include headers in our outbound checklists.

Along with this, (perhaps in another ticket) we should explore adding other headers, such as  "We're Hiring" ASCII art as well ;)

> #                                                       ___       _         
> #                                                      / (_)     | |        
> #     __ _  ___   ___ _ __ ___  ___   __ _  _____   __/ / _  ___ | |__  ___ 
> #    / _` |/ _ \ / __| '_ ` _ \/ __| / _` |/ _ \ \ / / / | |/ _ \| '_ \/ __|
> #   | (_| | (_) | (__| | | | | \__ \| (_| | (_) \ V / /  | | (_) | |_) \__ \
> #    \__, |\___(_)___|_| |_| |_|___(_)__, |\___/ \_/_/   | |\___/|_.__/|___/
> #     __/ |                           __/ |             _/ |                
> #    |___/                           |___/             |__/

**Comment by natalialuzuriaga** [comment]
License Header work is captured in this ticket: https://github.com/DSACMS/repo-scaffolder/issues/133

Ready for re-review: @decause-gov

**Review by decause-gov — APPROVED** [review]
What an *incredible* body of work you all have accomplished this summer!!! I haven't seen all of the new workflows in one place like this yet, and it has raised the floor of our baseline significantly! We have added so much information, and automated the gathering of that information as well. Excellent OSPO work, love to see it!

LGTML +1 🚢 ⚓

**Pull request merged**
